Repository MLGMAG/IASA_Organiser, pull requests merged in 2020-11, with the labels that each got.

#3 [Refactoring] Format code and remove redundant ';'
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Calendar.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Event.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Human.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Link.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Priority.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Tag.java
Labels: refactoring

#4 [Data Manager] Recode interface hierarchy
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/data/ArrayDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/data/GenericDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/data/impl/DefaultArrayDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/data/impl/EventStore.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/GeneralTests.java
Labels: question, refactoring

#5 [FileDataManagerTest] Refactor tests
  src/test/java/ua/kpi/iasa/IASA_Organiser/service/data/FileDataManagerIntegrationTest.java
Labels: refactoring

#6 [FileDataManager] Fix tests and recode isChanged variable
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/data/FileDataManager.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/service/data/FileDataManagerTest.java
Labels: refactoring

#9 [Place Model] Fix hashcode and add setter to field
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Place.java
Labels: refactoring

#10 [Event Model] Add getters to dome fields
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Event.java
Labels: enhancement

#13 [Console Manager] Fix change event
  src/main/java/ua/kpi/iasa/IASA_Organiser/view/ConsoleManager.java
Labels: bug

#14 [Builder] Add tests
  src/test/java/ua/kpi/iasa/IASA_Organiser/service/EventBuilderTest.java
Labels: enhancement

#37 [UML] Update old umls
  src/main/resources/UML/Controller.pdf
  src/main/resources/UML/IASA_Organiser_Controller.pdf
  src/main/resources/UML/IASA_Organiser_Model.pdf
  src/main/resources/UML/IASA_Organiser_UUCD.pdf
  src/main/resources/UML/Model.pdf
  src/main/resources/UML/UUCD.pdf
Labels: enhancement

#41 [DataManager] Add ArrayListDataManager Impl
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultArrayListDataManager.java
Labels: enhancement

#29 [Controller] Add unit tests
  src/test/java/ua/kpi/iasa/IASA_Organiser/controller/ControllerTest.java
Labels: testing

#33 [Controller] Change mathod naming
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/Controller.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/view/ConsoleManager.java
Labels: refactoring

#38 [Model] Remove redundant model - Type
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Type.java
Labels: refactoring

#39 [Controller] Generalize EventBuilder
  src/main/java/ua/kpi/iasa/IASA_Organiser/view/ConsoleManager.java
Labels: refactoring

#43 [Event] Change equals from comapring all fields to compare by ID
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Event.java
Labels: bug

#45 [Deprecated] Mark all methods chain to deprecated
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/ArrayDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/GenericDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultArrayDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/EventStore.java
Labels: refactoring

#47 [Deprecated] Mark all methods chain to deprecated
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultArrayDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultArrayListDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
Labels: refactoring

#44 Tanyas branch
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/util/CreationUtility.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/view/ConsoleManager.java
Labels: bug, enhancement, refactoring

#48 [ListDataManager] Add impl
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/ListDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultArrayListDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultListDataManager.java
Labels: enhancement

#49 [DefaultFileDataManager] Change file path
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
Labels: refactoring

#50 [EventService] Recode instantiation and add unit tests
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/ServiceTest.java
Labels: refactoring, testing

#51 [ServiceTest] File management
  src/test/java/ua/kpi/iasa/IASA_Organiser/serivce/ServiceTest.java
Labels: refactoring

#59 [DefaultFileDataManager] Extract all utility logic
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/util/FileUtility.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerIntegrationTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerTest.java
Labels: enhancement, refactoring

#53 [CalendarService] Add sorting and searching API
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/Controller.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Priority.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
Labels: enhancement

#62 [EventService] Add logging info
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
Labels: enhancement

#65 [Code] Format code
  src/main/java/ua/kpi/iasa/IASA_Organiser/builder/BuilderDirector.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/Controller.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/GenericDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/ListDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/util/CreationUtility.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/view/ConsoleManager.java
Labels: formatting

#66 [FileDataMaganer] Impl encapsulation and separate init logic
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/util/FileUtility.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerIntegrationTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerTest.java
Labels: refactoring

#68 [DefaultFileDataManager] Optimize some code and fix unit tests
  pom.xml
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerTest.java
Labels: refactoring, testing

#72 [DefaultFileDataManager] Code formatting and add logging
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
Labels: enhancement, refactoring

#71 [FileUtility] Add unit tests
  src/test/java/ua/kpi/iasa/IASA_Organiser/util/FileUtilityTest.java
Labels: testing

#70 [FileUtility] Fix issue #58 and add logging
  src/main/java/ua/kpi/iasa/IASA_Organiser/util/FileUtility.java
Labels: refactoring

#73 [FileUtilityTests] Add integration test and unit test
  src/test/java/ua/kpi/iasa/IASA_Organiser/util/FileUtilityIntegrationTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/util/FileUtilityTest.java
Labels: testing

#74 [.gitignore] Ignore all files in resources/data folder
  .gitignore
Labels: enhancement

#75 [FileUtility] Hotfix
  src/main/java/ua/kpi/iasa/IASA_Organiser/util/FileUtility.java
Labels: bug

#77 [IntegrationTest] Add integration tests to DefaultFileDataManager
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerIntegrationTest.java
Labels: testing

#76 [Logger] Add logging stream to file
  .gitignore
  src/main/resources/logback.xml
Labels: enhancement

#80 [CalendarServiceTest] Add unit tests, logging and rename some methods
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/Controller.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/serivce/CalendarServiceTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/serivce/EventServiceTest.java
Labels: refactoring, testing

#78 [DefaultFileDataManager] Transactionality
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/util/FileUtility.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/util/FileUtilityTest.java
Labels: enhancement, refactoring

#86 [Builder] Recode EventBuilder and optimize code
  src/main/java/ua/kpi/iasa/IASA_Organiser/builder/Builder.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/builder/BuilderDirector.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/builder/EventBuilder.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/view/ConsoleManager.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerIntegrationTest.java
Labels: formatting, refactoring

#81 [CalendarService] Add API
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/Controller.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
Labels: enhancement

#83 [CalendarPagination] Add pagination API
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarPaginationService.java
Labels: enhancement

#93 [Maven] Add dep version links and fix issue #87
  pom.xml
Labels: bug, refactoring

#96 [CalendarService] Remove redundant methods
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
Labels: refactoring

#97 [FileUtility] Remove redundant import
  src/main/java/ua/kpi/iasa/IASA_Organiser/util/FileUtility.java
Labels: refactoring

#98 [toString] Fix toString in some classes
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Event.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Human.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Link.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Place.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Tag.java
Labels: refactoring

#100 [EventService] Testing
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/service/EventServiceTest.java
Labels: testing

#109 [Tasks] Mark TR as completed
  README.md
Labels: refactoring

#111 [EventType] Add Enum
  pom.xml
  src/main/java/ua/kpi/iasa/IASA_Organiser/builder/BuilderDirector.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/builder/EventBuilder.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Event.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Type.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/util/CreationUtility.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/view/ConsoleManager.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/builder/EventBuilderTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerIntegrationTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/service/CalendarServiceTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/service/EventServiceTest.java
Labels: refactoring

#113 [Builder] Add documentation
  src/main/java/ua/kpi/iasa/IASA_Organiser/builder/EventBuilder.java
Labels: documentation
