Repository MLGMAG/IASA_Organiser, pull requests merged in 2020-12, with the labels that each got.

#115 [DefaultFIleDataManager] Add documentation
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerTest.java
Labels: documentation

#118 [SpringContext] Add spring context configuration
  pom.xml
  src/main/java/ua/kpi/iasa/IASA_Organiser/Main.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/Controller.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarPaginationService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/view/ConsoleManager.java
  src/main/resources/spring-config/application.properties
Labels: enhancement

#120 [SpringData] Add API for PostgreSql DB
  pom.xml
  src/main/java/ua/kpi/iasa/IASA_Organiser/Main.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/builder/EventBuilder.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/config/PersistenceConfiguration.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/Controller.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/ArrayDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/FileDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/GenericDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/ListDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultArrayDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultListDataManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/data/impl/EventStore.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Calendar.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Event.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Human.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Link.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Place.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Tag.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/repository/EventRepository.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarPaginationService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/util/CreationUtility.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/util/FileUtility.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/view/ConsoleManager.java
  src/main/resources/spring-config/application.properties
  src/test/java/ua/kpi/iasa/IASA_Organiser/builder/EventBuilderTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerIntegrationTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/data/impl/DefaultFileDataManagerTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/service/CalendarServiceTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/service/EventServiceTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/util/FileUtilityIntegrationTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/util/FileUtilityTest.java
Labels: enhancement, refactoring

#121 [SpringMVC] Add Spring MVC impl
  pom.xml
  src/main/java/ua/kpi/iasa/IASA_Organiser/Main.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/builder/EventBuilder.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/config/ConfigWebMVC.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/config/MainApplication.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/CalendarController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/Controller.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/EventController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/MainController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Event.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/util/CreationUtility.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/view/ConsoleManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/view/GUIManager.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/view/View.java
  src/main/resources/assets/templates/index.html
  src/test/java/ua/kpi/iasa/IASA_Organiser/builder/EventBuilderTest.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/controller/ControllerTest.java
Labels: enhancement, refactoring

#123 [Rest] Add REST API to human
  src/main/java/ua/kpi/iasa/IASA_Organiser/config/ConfigWebMVC.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Human.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/repository/HumanRepository.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/rest/HumanRestController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarPaginationService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/HumanService.java
Labels: enhancement

#124 [Frontend] Config resources and add Bootstrap 5 styling to index
  src/main/java/ua/kpi/iasa/IASA_Organiser/config/ConfigWebMVC.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/MainController.java
  src/main/resources/assets/static/css/main.css
  src/main/resources/assets/templates/fragments/templates.html
  src/main/resources/assets/templates/index.html
  src/main/resources/assets/templates/other/index.html
Labels: enhancement, refactoring

#125 [Frontent] Add humanList page
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/HumanController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/rest/HumanRestController.java
  src/main/resources/assets/templates/fragments/templates.html
  src/main/resources/assets/templates/human/humanList.html
Labels: enhancement

#127 [Model] Add G&S to id field and rewrite allArgsConstructor
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Link.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Place.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Tag.java
Labels: refactoring

#126 [Frontend] Add CRUD API to humanController
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/HumanController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/HumanService.java
  src/main/resources/assets/static/css/main.css
  src/main/resources/assets/templates/human/humanAdd.html
  src/main/resources/assets/templates/human/humanList.html
  src/main/resources/assets/templates/human/humanUpdate.html
  src/main/resources/assets/templates/human/humanView.html
Labels: enhancement

#128 [Rest] Add REST API to Event
  pom.xml
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/EventController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/rest/EventRestController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/HumanService.java
Labels: refactoring

#129 [HumanAPI] Code refactoring and update hibernate config
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/HumanController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Event.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Human.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Priority.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/repository/HumanRepository.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/HumanService.java
  src/main/resources/assets/templates/human/humanList.html
  src/main/resources/assets/templates/human/humanView.html
Labels: refactoring

#131 [ManyToMany] Add posibility to add invite human to event
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/EventController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/HumanController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Event.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/model/Human.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/repository/HumanRepository.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/HumanService.java
  src/main/resources/assets/templates/event/eventUpdate.html
  src/main/resources/assets/templates/event/eventView.html
  src/main/resources/assets/templates/human/humanView.html
Labels: enhancement, refactoring

#122 [DataBase] Add init database and data files
  src/main/resources/database/initDB.sql
  src/main/resources/database/initData.sql
Labels: enhancement

#134 [Feature] Add events with place and without
  src/main/java/ua/kpi/iasa/IASA_Organiser/config/ConfigWebMVC.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/main/resources/assets/static/js/placeForm.js
  src/main/resources/assets/templates/event/eventAdd.html
  src/main/resources/assets/templates/event/eventUpdate.html
  src/main/resources/assets/templates/event/eventView.html
Labels: enhancement

#139 [MVC] Configure beans
  src/main/java/ua/kpi/iasa/IASA_Organiser/config/ConfigWebMVC.java
Labels: refactoring

#140 [Optional] Optimize optional handling
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/HumanService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/LinkService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/TagService.java
Labels: refactoring

#142 [Human] Add posibility to leave event
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/HumanController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/HumanService.java
  src/main/resources/assets/templates/human/humanView.html
Labels: enhancement

#143 [Tomcat] Add embedded tomcat support
  pom.xml
  src/main/java/ua/kpi/iasa/IASA_Organiser/Application.java
Labels: enhancement

#144 [Boot] Update branch
  pom.xml
  src/main/java/ua/kpi/iasa/IASA_Organiser/Application.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/MainApplication.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/config/MainApplication.java
  src/main/resources/spring-config/application.properties
Labels: enhancement

#146 [Tests] Refactor EventService and add tests
  pom.xml
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/EventService.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/service/EventServiceTest.java
Labels: testing

#145 [CalendarService] Add documentation
  src/main/java/ua/kpi/iasa/IASA_Organiser/controller/Controller.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/CalendarService.java
Labels: documentation

#147 [Tests] Refactor HumanService and add tests
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/HumanService.java
  src/test/java/ua/kpi/iasa/IASA_Organiser/service/HumanServiceTest.java
Labels: testing

#148 [HumanRest] Add possibility to leave and join events
  src/main/java/ua/kpi/iasa/IASA_Organiser/rest/HumanRestController.java
Labels: enhancement

#149 Tags and links rest api
  src/main/java/ua/kpi/iasa/IASA_Organiser/rest/LinkRestController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/rest/TagRestController.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/LinkService.java
  src/main/java/ua/kpi/iasa/IASA_Organiser/service/TagService.java
Labels: enhancement
